import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Projeto teste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>Cabeçado da aplicação</header>
        <hr />
        {children}
        <hr />
        <footer>Rodapé da aplicação</footer>
      </body>
    </html>
  );
}
